name: reminder

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Reminder'
        run: npm install && npm run Reminder
