name: 'reminder'

on:
#  push:
  schedule:
    - cron: '25 8 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Run reminder'
        run: bash ./reminder.sh
